name: CI/CD
on:
  push:
    branches: [main]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: prisma generate
        run: bunx prisma generate

      - name: run tests
        run: bun test
